[project]
name = "werr"
version = "0.1.0"
description = "A python project task runner"
readme = "README.md"
requires-python = ">=3.13"
scripts = { "werr" = "werrlib.main:console_entry" }
dependencies = [
    "rich-argparse>=1.7.2",
]

[dependency-groups]
dev = [
    "isort>=7.0.0",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
    "ty>=0.0.9",
]

[tool.uv]
package = true

[tool.werr]
task.check = [
    "black --check {project}",
    "isort --check {project}",
    "ruff check {project}",
    "ty check {project}",
]
task.fix = [
    "black {project}",
    "isort {project}",
    "ruff check --fix {project}",
]
